# Exercise 3: Get to know pandas

pandas is an open-source library providing intuitive data structures for data analysis, data transformation, cleaning, and, with the help of matplotlib, simple data visualizations.

Most pandas' functionality is based on the numpy library, which is a optimized library providing efficient data structures and mathematical functions.

For all tasks within this JupyterNotebook refer to the extensive [user guide](https://pandas.pydata.org/docs/user_guide/index.html) and [API](https://pandas.pydata.org/docs/reference/index.html).

To use pandas simply import it like in the following code cell. Typically, this library is aliased with `pd`. It became the de-facto standard to import it with this alias.

In [1]:
import pandas as pd

An important datastructure within pandas are pandas `Series`. 

They represent a one-dimensional data structure utilized to store a sequence of data (for example, a single column of a table).

<div class="alert alert-info" role="alert">

**Task 1**:
    
Create a pandas `Series` using the variable `lectures`.

</div>

In [2]:
lectures = [
    "Course Introduction",
    "KDD Introduction",
    "Getting To Know Your Data",
    "Data Preprocessing",
    "OLAP",
    "Frequent Pattern",
    "Classification",
    "Cluster",
    "Outlier",
]

In [3]:
lectures = [
    "Course Introduction",
    "KDD Introduction",
    "Getting To Know Your Data",
    "Data Preprocessing",
    "OLAP",
    "Frequent Pattern",
    "Classification",
    "Cluster",
    "Outlier",
]

lecture_series = pd.Series(lectures)
lecture_series

0          Course Introduction
1             KDD Introduction
2    Getting To Know Your Data
3           Data Preprocessing
4                         OLAP
5             Frequent Pattern
6               Classification
7                      Cluster
8                      Outlier
dtype: object

Another significant data structure are the two-dimensional pandas `DataFrames`.

These are typically used to represent tables and internally employ pandas `Series` to depict columns.

<div class="alert alert-info" role="alert">

**Task 2:**
    
Create a pandas `DataFrame` using the `Series` you have created. Name the `Series` column `Lecture Name`.

</div>

In [4]:
lecture_name_df = pd.DataFrame(lecture_series, columns=["Lecture Name"])
lecture_name_df

                Lecture Name
0        Course Introduction
1           KDD Introduction
2  Getting To Know Your Data
3         Data Preprocessing
4                       OLAP
5           Frequent Pattern
6             Classification
7                    Cluster
8                    Outlier

In [22]:
lecture_df = pd.DataFrame(lecture_series, columns=["Lecture Name"])
lecture_df

                Lecture Name
0        Course Introduction
1           KDD Introduction
2  Getting To Know Your Data
3         Data Preprocessing
4                       OLAP
5           Frequent Pattern
6             Classification
7                    Cluster
8                    Outlier

Since a `DataFrame`is two-dimensional you can also add more than one column.

<div class="alert alert-info" role="alert">

**Task 3:**
    
Add the column `Status` to your `DataFrame`

</div>

In [6]:
status = [True, True, False, False, False, False, False, False, False]
lecture_name_df["Status"] = status
lecture_name_df

                Lecture Name  Status
0        Course Introduction    True
1           KDD Introduction    True
2  Getting To Know Your Data   False
3         Data Preprocessing   False
4                       OLAP   False
5           Frequent Pattern   False
6             Classification   False
7                    Cluster   False
8                    Outlier   False

In [23]:
status = [True, True, False, False, False, False, False, False, False]
lecture_df["Status"] = status

A `DataFrame` may hold many rows. Viewing the whole `DataFrame` at once might not always be the best idea. 

However, it is possible to only view the first or the last couple of rows. 

<div class="alert alert-info" role="alert">

**Task 4:**
    
Use `head()` and `tail()` to take a look at the first and last couple of rows of your `DataFrame`.

</div>

In [7]:
lecture_name_df.head()

                Lecture Name  Status
0        Course Introduction    True
1           KDD Introduction    True
2  Getting To Know Your Data   False
3         Data Preprocessing   False
4                       OLAP   False

In [8]:
lecture_name_df.tail()

       Lecture Name  Status
4              OLAP   False
5  Frequent Pattern   False
6    Classification   False
7           Cluster   False
8           Outlier   False

In [ ]:
lecture_df.head()

In [ ]:
lecture_df.tail()

In addition to data, it is also possible to look up fundamental information about a `DataFrame`.

<div class="alert alert-info" role="alert">

**Task 5:**
    
Determine the number of rows and the number of columns your `DataFrame` has.

</div>

In [11]:
print(
    f"Number of rows: {lecture_name_df.shape[0]}",
    f"Number of columns: {lecture_name_df.shape[1]}",
    sep="\n"
)

Number of rows: 9
Number of columns: 2

In [ ]:
print(
    f"Number of rows: {lecture_df.shape[0]}",
    f"Number of columns: {lecture_df.shape[1]}",
    sep="\n",
)

<div class="alert alert-info" role="alert">

**Task 6:**
    
Get the names of all columns your `DataFrame` has.

</div>

In [12]:
lecture_name_df.columns

Index(['Lecture Name', 'Status'], dtype='object')

In [ ]:
lecture_df.columns

It is possible to select one or more specific columns.

<div class="alert alert-info" role="alert">

**Task 7:**
    
Select only the `Lecture Name` column of your `DataFrame`.

</div>

In [13]:
lecture_name_df["Lecture Name"]

0          Course Introduction
1             KDD Introduction
2    Getting To Know Your Data
3           Data Preprocessing
4                         OLAP
5             Frequent Pattern
6               Classification
7                      Cluster
8                      Outlier
Name: Lecture Name, dtype: object

In [ ]:
lecture_df["Lecture Name"]

Just as selecting individual columns is possible, one can also select rows.

<div class="alert alert-info" role="alert">

**Task 8:**
    
Select only the second row of your `DataFrame`.

</div>

In [19]:
lecture_name_df.iloc[2]

Lecture Name    Getting To Know Your Data
Status                              False
Name: 2, dtype: object

In [ ]:
lecture_df.loc[2]

<div class="alert alert-info" role="alert">

**Task 9:**
    
Select all rows of your `DataFrame` starting with the third row.

</div>

In [20]:
lecture_name_df[3:]

         Lecture Name  Status
3  Data Preprocessing   False
4                OLAP   False
5    Frequent Pattern   False
6      Classification   False
7             Cluster   False
8             Outlier   False

In [24]:
lecture_df.loc[3:]

         Lecture Name  Status
3  Data Preprocessing   False
4                OLAP   False
5    Frequent Pattern   False
6      Classification   False
7             Cluster   False
8             Outlier   False

If there are two pandas `DataFrame`s that are associated with each other, there might be benefits to merge them. This merge is called a `join`.

<div class="alert alert-info" role="alert">
    
**Task 10:**
    
Join the `DataFrame`s `orders_df` and `customers_df`. Make sure that all orders are included in the joined `DataFrame`. Customers should only be included if they are part of an order.

</div>

In [25]:
orders_df = pd.DataFrame(
    data={
        "Order_ID": [1, 2, 3, 4, 5],
        "Customer_ID": [23, 19, 95, 34, 89],
    }
)

customers_df = pd.DataFrame(
    data={
        "Customer_ID": [6, 19, 23, 34, 77, 89, 95],
        "Customer_First_Name": [
            "John",
            "Alice",
            "Bob",
            "Dylan",
            "Catherine",
            "Eva",
            "Frank",
        ],
        "Customer_Last_Name": [
            "Doe",
            "Smith",
            "Johnson",
            "Brown",
            "Black",
            "White",
            "Green",
        ],
    }
)

print(orders_df.head())
print(customers_df.head())

   Order_ID  Customer_ID
0         1           23
1         2           19
2         3           95
3         4           34
4         5           89
   Customer_ID Customer_First_Name Customer_Last_Name
0            6                John                Doe
1           19               Alice              Smith
2           23                 Bob            Johnson
3           34               Dylan              Brown
4           77           Catherine              Black

In [26]:
merged_df = orders_df.merge(customers_df)
merged_df

   Order_ID  Customer_ID Customer_First_Name Customer_Last_Name
0         1           23                 Bob            Johnson
1         2           19               Alice              Smith
2         3           95               Frank              Green
3         4           34               Dylan              Brown
4         5           89                 Eva              White

In [ ]:
orders_with_customers_df = pd.merge(
    orders_df, customers_df, on="Customer_ID", how="inner"
)
orders_with_customers_df.head(15)

All of this represents merely a small excerpt of what is possible with pandas. In the coming weeks, you will become acquainted with many more functions of pandas during the exercises. Remember that you have access to the [user guide](https://pandas.pydata.org/docs/user_guide/index.html) and [API](https://pandas.pydata.org/docs/reference/index.html).